id = "versionlens"
name = "Version Lens"
version = "0.0.1"
schema_version = 1
authors = ["Imamuzzaki Abu Salam <imamuzzaki@gmail.com>"]
description = "Display version information for dependencies in package files (package.json, Cargo.toml, etc.)"
repository = "https://github.com/ImBIOS/versionlens"
